const router = require('express').Router()
const {getQuestion,createUser,handleGame,getgiaodien} = require('../controller/test')
router.route('/abc')
    .get(getgiaodien)  
router.route('/game')
    .get(getQuestion)  
    .post(createUser)
router.route('/handle/:id')
    .get(handleGame)  
module.exports = router